apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      volumes:
      - name: regcred
        secret:
          secretName: regcred
          items:
          - key: dockerconfig.json
            path: config.json
      containers:
      - image: gcr.io/kaniko-project/executor:debug
        name: guestbook-ui
        args:
        - --context=https://github.com/nekia/airtng-node
        - --destination=nekia/my-airtng-node:v2
        volumeMounts:
          - name: regcred
            mountPath: /kaniko/.docker/
        ports:
        - containerPort: 8080
